version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: windnewsmapper_db
    environment:
      POSTGRES_USER: winduser
      POSTGRES_PASSWORD: windpass
      POSTGRES_DB: windnewsdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - windnews_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U winduser -d windnewsdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: windnewsmapper_backend
    environment:
      DATABASE_URL: postgresql://winduser:windpass@db:5432/windnewsdb
      CORS_ORIGINS: http://localhost:5173,http://localhost:3000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    networks:
      - windnews_network
    depends_on:
      db:
        condition: service_healthy
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    container_name: windnewsmapper_frontend
    environment:
      VITE_API_URL: http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    networks:
      - windnews_network
    depends_on:
      - backend
    command: npm run dev -- --host

networks:
  windnews_network:
    driver: bridge

volumes:
  postgres_data:
