name: CI/CD - Development

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

env:
  PYTHON_VERSION: '3.11'
  NODE_VERSION: '18'

jobs:
  # ================================
  # Backend Linting and Tests
  # ================================
  backend-lint:
    name: Backend - Lint (Python)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Cache pip packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black isort
          pip install -r requirements.txt

      - name: Run Black (code formatter check)
        working-directory: ./backend
        run: black --check --diff app/

      - name: Run isort (import sorting check)
        working-directory: ./backend
        run: isort --check-only --diff app/

      - name: Run Flake8 (linting)
        working-directory: ./backend
        run: flake8 app/ --max-line-length=120 --exclude=__pycache__,venv

  backend-test:
    name: Backend - Tests (pytest)
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Cache pip packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-asyncio pytest-cov
          pip install -r requirements.txt

      - name: Run pytest
        working-directory: ./backend
        env:
          DATABASE_URL: postgresql://testuser:testpass@localhost:5432/testdb
        run: |
          # Create tests directory if it doesn't exist
          mkdir -p tests
          # Run tests if they exist, otherwise skip
          if [ -d "tests" ] && [ "$(ls -A tests/*.py 2>/dev/null)" ]; then
            pytest tests/ -v --cov=app --cov-report=xml --cov-report=term
          else
            echo "No tests found - skipping test execution"
            echo "TODO: Add pytest tests in backend/tests/"
          fi

      - name: Upload coverage reports
        uses: codecov/codecov-action@v4
        if: always()
        with:
          files: ./backend/coverage.xml
          flags: backend
          name: backend-coverage

  # ================================
  # Frontend Linting and Build
  # ================================
  frontend-lint:
    name: Frontend - Lint (ESLint)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Run ESLint
        working-directory: ./frontend
        run: npm run lint

  frontend-build:
    name: Frontend - Build (TypeScript + Vite)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Build production bundle
        working-directory: ./frontend
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: frontend/dist/
          retention-days: 7

  # ================================
  # Docker Build
  # ================================
  docker-build:
    name: Docker - Build Images
    runs-on: ubuntu-latest
    needs: [backend-lint, backend-test, frontend-lint, frontend-build]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: false
          tags: windnewsmapper-backend:dev
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build frontend image (development)
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          target: development
          push: false
          tags: windnewsmapper-frontend:dev
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # ================================
  # Deploy to Development
  # ================================
  deploy-dev:
    name: Deploy to Development (dev.windnews.rabciak.site)
    runs-on: ubuntu-latest
    needs: [docker-build]
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    environment:
      name: development
      url: https://dev.windnews.rabciak.site

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy notification
        run: |
          echo "🚀 Deploying to development environment..."
          echo "⚠️  Deployment to OVH not yet configured"
          echo "📝 TODO: Configure SSH access and deployment scripts"

      # Uncomment when OVH deployment is ready
      # - name: Deploy to OVH via SSH
      #   uses: appleboy/ssh-action@v1.0.0
      #   with:
      #     host: ${{ secrets.DEV_SERVER_HOST }}
      #     username: ${{ secrets.DEV_SERVER_USER }}
      #     key: ${{ secrets.DEV_SERVER_SSH_KEY }}
      #     script: |
      #       cd /opt/windnewsmapper-dev
      #       git pull origin develop
      #       docker-compose -f docker-compose.dev.yml pull
      #       docker-compose -f docker-compose.dev.yml up -d --build
      #       docker-compose -f docker-compose.dev.yml exec -T backend alembic upgrade head

      # - name: Health check
      #   run: |
      #     sleep 10
      #     curl -f https://dev.windnews.rabciak.site/health || exit 1
